debug: true
plugins:
  - meilisync.plugin.Plugin
progress:
  type: file
source:
  type: mysql
  host: localhost
  port: 3366
  user: root
  password: root
  database: dispute_explorer
meilisearch:
  api_url: http://localhost:7700
  api_key: 40185ac3f6804d9e0e08e158380b3f548b7c5b8a88bdb7b6608c82c0838a26d4
sync:
  - table: dispute_game
    index: disputegametest
    plugins:
      - meilisync.plugin.Plugin
    full: true
    fields:
      id:
      sync_block_id:
      blockchain:
      block_time:
      block_number:
      block_hash:
      block_log_indexed:
      tx_index:
      tx_hash:
      contract_address:
      game_contract:
      game_type:
      l2_block_number:
      status:
  - table: game_claim_data
    index: gameclaimtest
    full: true
    fields:
      id:
      game_contract:
      data_index:
      parent_index:
      countered_by:
      claimant:
      bond:
      claim:
      position:
      clock:
      output_block:
  - table: game_credit
    index: gamecredittest
    full: true
    fields:
      id:
      game_contract:
      address:
      credit:
  - table: sync_events
    index: gameevents
    full: true
    fields:
      id:
      sync_block_id:
      blockchain:
      block_time:
      block_number:
      block_hash:
      block_log_indexed:
      tx_index:
      tx_hash:
      event_name:
      event_hash:
      contract_address:
      data:
      status:




