debug: true
plugins:
  - meilisync.plugin.Plugin
progress:
  type: file
source:
  type: mysql
  host: localhost
  port: 3367
  user: root
  password: root
  database: dispute_explorer
meilisearch:
  api_url: http://localhost:7701
  api_key: 2b85b8c251421e43808ee9e20e34e6b001268cee726845d3ba9b40a83fa728e9
sync:
  - table: dispute_game
    index: disputegames
    plugins:
      - meilisync.plugin.Plugin
    full: true
    fields:
      id:
      sync_block_id:
      blockchain:
      block_time:
      block_number:
      block_hash:
      block_log_indexed:
      tx_index:
      tx_hash:
      contract_address:
      game_contract:
      game_type:
      l2_block_number:
      status:
  - table: game_claim_data
    index: gameclaims
    full: true
    fields:
      id:
      game_contract:
      data_index:
      parent_index:
      countered_by:
      claimant:
      bond:
      claim:
      position:
      clock:
      output_block:
  - table: game_credit
    index: gamecredits
    full: true
    fields:
      id:
      game_contract:
      address:
      credit:
  - table: sync_events
    index: syncevents
    full: true





