debug: true
plugins:
  - meilisync.plugin.Plugin
progress:
  type: file
source:
  type: mysql
  host: localhost
  port: 3366
  user: root
  password: root
  database: dispute_explorer
meilisearch:
  api_url: http://localhost:7700
  api_key: 6914dc950098e39609cafc9abbced1cd02d7509b54b7ad1cd18ced8cad01f9be
sync:
  - table: dispute_game
    index: disputegame
    plugins:
      - meilisync.plugin.Plugin
    full: true
    fields:
      id:
      sync_block_id:
      blockchain:
      block_time:
      block_number:
      block_hash:
      block_log_indexed:
      tx_index:
      tx_hash:
      contract_address:
      game_contract:
      game_type:
      l2_block_number:
      status:
  - table: game_claim_data
    index: gameclaim
    full: true
    fields:
      id:
      game_contract:
      data_index:
      parent_index:
      countered_by:
      claimant:
      bond:
      claim:
      position:
      clock:
      output_block:
  - table: game_credit
    index: gamecredit
    full: true
    fields:
      id:
      game_contract:
      address:
      credit:
  - table: sync_events
    index: syncevents
    full: true





