debug: true
plugins:
  - meilisync.plugin.Plugin
progress:
  type: file
source:
  type: mysql
  host: localhost
  port: 3367
  user: root
  password: root
  database: dispute_explorer
meilisearch:
  api_url: http://localhost:7700
  api_key: 56313adcb3ebc9220c6b225f7a17d4a1f84183a64ddecac62d179486ed1f0114
sync:
  - table: dispute_game
    index: disputegames
    plugins:
      - meilisync.plugin.Plugin
    pk: id
    full: true
    fields:
      id:
      sync_block_id:
      blockchain:
      block_time:
      block_number:
      block_hash:
      block_log_indexed:
      tx_index:
      tx_hash:
      contract_address:
      game_contract:
      game_type:
      l2_block_number:
      status:
      on_chain_status:
      claim_data_len:
      get_len_status:
  - table: game_claim_data
    index: gameclaims
    pk: id
    full: true
    fields:
      id:
      game_contract:
      data_index:
      parent_index:
      countered_by:
      claimant:
      bond:
      claim:
      position:
      clock:
      output_block:
  - table: game_credit
    index: gamecredits
    pk: id
    full: true
    fields:
      id:
      game_contract:
      address:
      credit:
  - table: sync_events
    index: syncevents
    pk: id
    full: true
