version: "3"

services:

  postgres:
    container_name: postgres-game
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - "5435:5432"
    volumes:
      - ./pg-data:/var/lib/postgresql/data

  node1:
    container_name: dispute-explorer-backend
    image: ghcr.io/optimism-java/dispute-explorer:sha-0e9542b
    depends_on:
      - postgres
    environment:
      LOG_LEVEL: "info"
      LOG_FORMAT: "console"
      POSTGRESQL_DATA_SOURCE: "host=localhost port=5435 user=postgres password=postgres dbname=dispute_explorer sslmode=disable"
      MYSQL_MAX_IDLE_CONNS: "10"
      MYSQL_MAX_OPEN_CONNS: "20"
      MYSQL_CONN_MAX_LIFETIME: "3600"
      BLOCKCHAIN: "sepolia"
      L1_RPC_URL: "https://quaint-white-season.ethereum-sepolia.quiknode.pro/b5c30cbb548d8743f08dd175fe50e3e923259d30"
      FROM_BLOCK_NUMBER: "6034337"
      FROM_BLOCK_HASH: "0xafc3e42c5899591501d29649ffef0bfdec68f8d77e6d44ee00ef88cfb1a2f163"
      DISPUTE_GAME_PROXY_CONTRACT: "0x05F9613aDB30026FFd634f38e5C4dFd30a197Fa1"
    network_mode: host

  meiliSearch:
    container_name: meilisearch
    image: getmeili/meilisearch:v1.8
    environment:
      - MEILI_MASTER_KEY=123456
    ports:
      - "7700:7700"
    volumes:
      - ./meili_data:/meili_data

  meiliSync:
    platform: linux/x86_64
    image: long2ice/meilisync:sha-fc1877d
    volumes:
      - ./config.yml:/meilisync/config.yml
    network_mode: host

  mysql1:
    container_name: mysql1
    image: mysql:8.0.28
    environment:
      MYSQL_ROOT_PASSWORD: "root"
    ports:
      - "3366:3306"
    volumes:
      - ./mysql1/datadir:/var/lib/mysql
