version: "3"

services:
  mysql:
    container_name: mysql
    image: mysql:8.4.2
    environment:
      MYSQL_ROOT_PASSWORD: "root"
    restart: always
    ports:
      - "3367:3306"
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 45s
      interval: 10s
      retries: 10
    volumes:
      - ./mysql/datadir:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  node1:
    container_name: dispute-explorer-backend
    image: ghcr.io/optimism-java/dispute-explorer:sha-a666742
    restart: on-failure
    depends_on:
      mysql:
        condition: service_healthy
    env_file:
      - ../.env
    ports:
      - "8080:8080"

  meiliSearch:
    container_name: meilisearch
    image: getmeili/meilisearch:v1.8
    restart: always
    depends_on:
      - mysql
      - node1
    environment:
      - MEILI_MASTER_KEY=123456
    ports:
      - "7700:7700"
    volumes:
      - ./meili_data:/meili_data

  meiliSync:
    platform: linux/x86_64
    image: long2ice/meilisync:sha-fc1877d
    restart: on-failure
    depends_on:
      - mysql
      - node1
      - meiliSearch
    volumes:
      - ./config.yml:/meilisync/config.yml
    network_mode: host

  frontend:
    image: ghcr.io/optimism-java/dispute-explorer-frontend:development
    restart: on-failure
    depends_on:
      - mysql
      - node1
      - meiliSearch
    environment:
      - ADMIN_KEY=123456
    ports:
      - "8888:80"
