version: "3"

services:

  mysql:
    container_name: mysql
    image: mysql:8.0.28
    environment:
      MYSQL_ROOT_PASSWORD: "root"
    ports:
      - "3367:3306"
    volumes:
      - ./mysql/datadir:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  node1:
    container_name: dispute-explorer-backend
    image: ghcr.io/optimism-java/dispute-explorer:sha-8918beb
    restart: on-failure
    depends_on:
      - mysql
    env_file:
      - ../.env
    network_mode: host




