version: "3"

services:

  mysql:
    container_name: mysql
    image: mysql:8.0.28
    environment:
      MYSQL_ROOT_PASSWORD: "root"
    restart: always
    ports:
      - "3367:3306"
    volumes:
      - ./mysql/datadir:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  node1:
    container_name: dispute-explorer-backend
    image: ghcr.io/optimism-java/dispute-explorer:sha-01ae5fc
    restart: on-failure
    depends_on:
      - mysql
    env_file:
      - ../.env
    network_mode: host

  meiliSearch:
    container_name: meilisearch
    image: getmeili/meilisearch:v1.8
    restart: always
    depends_on:
      - mysql
      - node1
    environment:
      - MEILI_MASTER_KEY=123456
    ports:
      - "7700:7700"
    volumes:
      - ./meili_data:/meili_data

  meiliSync:
    platform: linux/x86_64
    image: long2ice/meilisync:sha-fc1877d
    restart: on-failure
    depends_on:
      - mysql
      - node1
      - meiliSearch
    volumes:
      - ./config.yml:/meilisync/config.yml
    network_mode: host




