version: "3"

services:
  meiliSearch:
    container_name: meilisearch
    image: getmeili/meilisearch:v1.8
    depends_on:
      - mysql
      - node1
    environment:
      - MEILI_MASTER_KEY=123456
    ports:
      - "7701:7700"
    volumes:
      - ./meili_data:/meili_data

  meiliSync:
    platform: linux/x86_64
    image: long2ice/meilisync:sha-fc1877d
    depends_on:
      - mysql
      - node1
      - meiliSearch
    volumes:
      - ./config.yml:/meilisync/config.yml
    network_mode: host
