name: Check Markdown links
on:
  pull_request:
    paths:
      - '**.md'
  push:
    branches:
      - main
    paths:
      - '**.md'

jobs:
  markdown-link-check:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 20.x ]
    steps:
      - uses: actions/checkout@v3
      - uses: technote-space/get-diff-action@v6.1.2
        id: git_diff
        with:
          PATTERNS: |
            **/**.md
      - uses: gaurav-nelson/github-action-markdown-link-check@master
        with:
          folder-path: "docs"
          check-modified-files-only: "yes"
          use-quiet-mode: "yes"
          base-branch: "main"
        if: env.GIT_DIFF
